apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chat-demo
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/cptkirk/special-eureka:backend-0.0.2
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
        env:
        - name: PORT
          value: '3000'
        - name: REDIS_URL
          value: 'redis://chat-demo-valkey:6379'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chat-demo
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/cptkirk/special-eureka:frontend-0.0.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
